### ISSUE TITLE
[Milestone] First feature

### ISSUE THREAD

**Issue by jcbhmr** [jcbhmr/devcontainer-features#21]
- [x] Define what's eligible to be a feature #17 
- [x] Decide on what feature that could be #18 #16
- [x] Write an install.sh script for it
- [x] Make sure it's up-to-code and tested
- [ ] Publish it as a package manually using `workflow_dispatch`
- [ ] Get this feature repo added to the https://containers.dev/collections index

**Comment by jcbhmr** [comment]
@eitsupi anything i missed?

**Comment by eitsupi** [comment]
Thanks for bringing this forward!

As I have mentioned several times, Feature requires continuous maintenance, so ideally, it would be necessary to establish criteria and procedures for discontinuing as well as for adding, but I don't think it is necessary to do this from the beginning.

**Comment by jcbhmr** [comment]
> it would be necessary to establish criteria and procedures for discontinuing as well as for adding

❤️ thats why #17 is pinned and first on the list 😆

but if you want to jump the gun, we've got a deno discussion in #18 -- would be nice if https://github.com/denoland/deno/discussions/18144 had ✈️ taken off but alas... 😞

for other options, there's the llvm and cmake features in https://github.com/devcontainers-community/features/tree/jcbhmr-features/src (see for info https://github.com/devcontainers-community/features/issues/19#issuecomment-1530838427)

or open to any other ideas for a first feature 😊

**Comment by nanis94** [comment]
main

**Comment by jcbhmr** [comment]
Ok so #26 was merged thanks to @eitsupi! ❤️ next step is to run the publishing workflow manually to "release it" and then open a PR to add this index to the official feature index!

**Comment by eitsupi** [comment]
I think we should set and pass CI first.

**Comment by jcbhmr** [comment]
Are we ready to move forward? What else should I do? 😊

**Comment by eitsupi** [comment]
> Are we ready to move forward? What else should I do? 😊

Perhaps #25 needs to be completed?

**Comment by jcbhmr** [comment]
Yeah that's a good idea. 👍

**Comment by jcbhmr** [comment]
Got two features so far:
https://github.com/devcontainers-community/features-dart-sdk
https://github.com/devcontainers-community/features-cmake
